import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Anime Lover Library",
  description: "Generated by Akshay Charwekar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">{children}</html>;
}
