import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const roboto = Roboto({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "300", "400", "500", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Anime Lover Library",
  description: "Generated by Akshay Charwekar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "min-h-screen bg-gradient-to-b from-gray-800 to-gray-900 leading-relaxed text-white antialiased",
          roboto.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
